Error message
tannazma/prework pull request #2
Opened 2023-09-17 18:10 UTC by tannazma

2023-09-17 18:16 UTC, aghArdeshir requested changes

2023-09-17 18:16 UTC, aghArdeshir commented on index.html
> +          >Required Energy Units per week (RU)
The formatting is not beautiful. Please move the "gt" sign in the same line as label

2023-09-17 18:16 UTC, aghArdeshir commented on index.html
> +          >Area per solar panel in m² (AR)
The same is true with every other label

2023-09-17 18:16 UTC, aghArdeshir commented on styles.css
> +}
Wouldn't it make more sense to use `error-color` instead of red?

2023-09-19 08:57 UTC, tannazma commented on index.html
> +          >Required Energy Units per week (RU)
Done: https://github.com/tannazma/prework/pull/2/commits/d8d1ccc73d92eb359959e5332c5f3e9fd7cba0cf Thanks :)

2023-09-19 08:59 UTC, tannazma commented on styles.css
> +}
Sure and it's done https://github.com/tannazma/prework/pull/2/commits/947afb735d222ab81d4498be58fa5da9e5f78665

2023-09-19 10:00 UTC, aghArdeshir commented on styles.css
> +}
Sorry. I meant it would be better to use the same `error-color` css variable we had earlier. So every color that represents an error is the same in our app:
```
.error-message {
  color: var(--error-color);
}
```

2023-09-19 10:17 UTC, tannazma commented on styles.css
> +}
Sorry for misunderstanding here you are: https://github.com/tannazma/prework/pull/2/commits/a3e3fc529fad230d4ac56b83c10ce22480deacef

2023-09-19 10:26 UTC, tannazma commented on index.html
> +          >Area per solar panel in m² (AR)
Thanks

2023-09-19 10:26 UTC, merged